(ns p002)
;Even Fibonacci numbers
;Problem 2
;Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;By starting with 1 and 2, the first 10 terms will be:
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million,
; find the sum of the even-valued terms.
;xxf
;2016-05-04

(defn even-fib-sum[scope]
  (loop [i 1 j 1 s 0]
    (if (< j scope)
      (do
        ;(prn j)
        (if (even? j)
          (recur j (+ i j) (+ s j))
          (recur j (+ i j) s) ) )
      s) ) )
(even-fib-sum 4000000)
